project_name: jumphost
builds:
  - main: main.go
    binary: jumphost
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
archive:
  format: tar.gz
  files:
    - Readme.md
    - LICENSE
